import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const tmp = process.env.TEMP || process.env.TMP || root;
const rawTracks = readFileSync(join(tmp, 'mood_tracks.json'), 'utf8').replace(/^\uFEFF/, '');
const tracks = JSON.parse(rawTracks);
const tracksByName = new Map(tracks.map((entry) => [entry.name, entry]));

const TAB_META = [
  {
    id: 'bengali',
    label: 'Bengali',
    script: 'বাংলা',
    emoji: '🪔',
    tagline: 'Bangla band, adhunik and film — the hometown rotation.',
    artists: ['Anjan Dutt', 'Rupam Islam', 'Anupam Roy', 'Rupankar', 'Cactus', 'Fossils', 'Chandrabindoo'],
  },
  {
    id: 'hindi',
    label: 'Hindi',
    script: 'हिन्दी',
    emoji: '🎶',
    tagline: 'Film legends and modern voices from Kishore da to Arijit.',
    artists: [
      'Kishore Kumar',
      'Lata Mangeshkar',
      'Sonu Nigam',
      'A. R. Rahman',
      'Shreya Ghoshal',
      'Atif Aslam',
      'Pritam',
      'Vishal-Shekhar',
      'Arijit Singh',
      'Armaan Malik',
      'Jubin Nautiyal',
    ],
  },
  {
    id: 'english',
    label: 'English',
    script: 'EN',
    emoji: '🎸',
    tagline: 'Rock, pop and synth for the loud hours of a deadline.',
    artists: ['Elvis Presley', 'Pink Floyd', 'Queen', 'Linkin Park', 'Bruno Mars', 'Coldplay', 'Ed Sheeran', 'The Weeknd'],
  },
];

// Titles must survive a JS single-quoted string and `JSON.stringify` output.
const esc = (value) => JSON.stringify(String(value == null ? '' : value));

const tabs = TAB_META.map((meta) => {
  const groups = [];
  let songCount = 0;
  for (const artist of meta.artists) {
    const entry = tracksByName.get(artist);
    if (!entry || !entry.albums || entry.albums.length === 0) continue;
    const albums = [];
    for (const album of entry.albums) {
      if (!album.tracks || album.tracks.length === 0) continue;
      songCount += album.tracks.length;
      const songs = album.tracks.map((song) => {
        const line = [`            { id: ${esc(song.id)}, title: ${esc(song.ttl)}, dur: ${song.dur}`];
        if (song.feat) line.push(`, feat: ${esc(song.feat)}`);
        return `${line.join('')} },`;
      });
      const year = album.year ? `, year: ${JSON.stringify(String(album.year))}` : '';
      albums.push(
        `        {\n          id: ${esc(album.id)}, title: ${esc(album.title)}${year},\n          songs: [\n${songs.join('\n')}\n          ],\n        },`,
      );
    }
    if (albums.length === 0) continue;
    groups.push(
      `      {\n        artist: ${esc(entry.name)}, artistId: ${esc(entry.spotify)},\n        albums: [\n${albums.join('\n')}\n        ],\n      },`,
    );
  }
  const groupCount = groups.length;
  return { ...meta, groups, songCount, groupCount };
});

if (tabs.some((tab) => tab.groups.length === 0)) {
  console.error(`missing groups: ${tabs.map((tab) => `${tab.id}=${tab.groups.length}`).join(', ')}`);
  process.exit(1);
}

const focusSongs = [
  {
    title: 'lofi beats',
    artist: 'Spotify editorial · instrumental',
    url: 'https://open.spotify.com/playlist/37i9dQZF1DWWQRwui0ExPn',
  },
  {
    title: 'Deep Focus',
    artist: 'Spotify editorial · instrumental',
    url: 'https://open.spotify.com/playlist/37i9dQZF1DWZeKCadgRdKQ',
  },
  {
    title: 'Beast Mode',
    artist: 'Spotify editorial · instrumental',
    url: 'https://open.spotify.com/playlist/37i9dQZF1DX76Wlfdnj7AP',
  },
  {
    title: 'Peaceful Piano',
    artist: 'Spotify editorial · instrumental',
    url: 'https://open.spotify.com/playlist/37i9dQZF1DX4sWSpwq3LiO',
  },
];

const renderTab = (tab) =>
  `    {\n      id: ${esc(tab.id)},\n      label: ${esc(tab.label)},\n      script: ${esc(tab.script)},\n      emoji: ${esc(tab.emoji)},\n      tagline: ${esc(tab.tagline)},\n      groups: [\n${tab.groups.join('\n')}\n      ],\n    },`;

const renderFocus = () =>
  `    {\n      id: 'focus',\n      label: 'Focus',\n      script: '◎',\n      emoji: '🎧',\n      tagline: 'No lyrics, all flow — the instrumental lists for deep work.',\n      songs: [\n${focusSongs
        .map(
          (song) =>
            `        {\n          title: ${esc(song.title)},\n          artist: ${esc(song.artist)},\n          platform: 'spotify',\n          kind: 'playlist',\n          url: ${esc(song.url)},\n        },`,
        )
        .join('\n')}\n      ],\n    },`;

const chunks = [...tabs.map(renderTab), renderFocus()];

const header = `// ---------------------------------------------------------------------------
// Mood deck discography — GENERATED by scripts/mood-gen.mjs, do not hand-edit.
// Source: public Spotify embeds (tracks.json plan in %TEMP%). Every song plays
// full length from Spotify's own player; nothing is re-hosted. Regenerate with:
//   node scripts/mood-gen.mjs
// ---------------------------------------------------------------------------
export const moodContent = {
  tabs: [
${chunks.join('\n')}
  ],
};
`;

writeFileSync(join(root, '..', 'src', 'data', 'moodData.js'), header, 'utf8');

const meta = tabs.map((tab) => ({
  id: tab.id,
  label: tab.label,
  emoji: tab.emoji,
  tagline: tab.tagline,
  count: tab.songCount,
}));
meta.push({
  id: 'focus',
  label: 'Focus',
  emoji: '🎧',
  tagline: 'No lyrics, all flow — the instrumental lists for deep work.',
  count: focusSongs.length,
});

console.log(JSON.stringify({ tabs: tabs.map((tab) => ({ id: tab.id, groups: tab.groupCount, songs: tab.songCount })), meta }, null, 2));